#!/bin/bash
set -e

cd $(dirname $0)/..

TEMP_SOURCE_DIR=.tmp

trash -k -T ${TEMP_SOURCE_DIR}
mkdir -p ./components
mv ${TEMP_SOURCE_DIR}/github.com/rancher/docker-cli components/cli
mv ${TEMP_SOURCE_DIR}/github.com/rancher/docker components/engine
mv ${TEMP_SOURCE_DIR}/github.com/rancher/docker-ce-packaging components/packaging

cp VERSION components/cli/
cp VERSION components/engine/

#prepare_component() {
    #local name=$1
    #local url=$2

    #mkdir -p components/$name
    #rm -rf components/$name/*
    #curl -SL $url | tar --strip-components=1 -xzvf - -C components/$name
#}

#if [ -z "$CLI_VERSION" ] || [ -z "$ENGINE_VERSION" ] || [ -z "$PACKAGING_VERSION" ]; then
    #echo CLI_VERSION and ENGINE_VERSION and PACKAGING_VERSION must be set
    #exit 1
#fi

#CLI_REPO=${CLI_REPO:-"https://github.com/niusmallnan/cli"}
#ENGINE_REPO=${ENGINE_REPO:-"https://github.com/niusmallnan/moby"}
#PACKAGING_REPO=${PACKAGING_REPO:-"https://github.com/niusmallnan/docker-ce-packaging"}

#prepare_component cli ${CLI_REPO}/archive/${CLI_VERSION}.tar.gz
#prepare_component engine ${ENGINE_REPO}/archive/${ENGINE_VERSION}.tar.gz
#prepare_component packaging ${PACKAGING_REPO}/archive/${PACKAGING_VERSION}.tar.gz

#cp VERSION components/cli/
