#!/bin/bash
set -e

cd $(dirname $0)/..

echo "#!/bin/sh" > ./dist/publish.sh
chmod 755 ./dist/publish.sh
echo "github-release release --user niusmallnan --repo os-system-docker --tag ${VERSION} --pre-release" >> ${CURDIR}/dist/publish.sh
echo "github-release upload --user niusmallnan --repo os-system-docker --tag ${VERSION} --file ./dist/linux/docker-${VERSION}.tgz --name docker-amd64-${VERSION}.tgz" >> ${CURDIR}/dist/publish.sh
